#!/bin/bash

mkdir -p /var/log/v2ray
PORT=$((1000 + RANDOM))
sed -i "s/\"port\":\ 10086/\"port\":\ ${PORT}/g" "/etc/v2ray/config.json"
UUID=$(cat /proc/sys/kernel/random/uuid)
sed -i "s/23ad6b10-8d1a-40f7-8ad0-e3e35cd38297/${UUID}/g" "/etc/v2ray/config.json"
systemctl enable v2ray
systemctl start v2ray
echo "port: $PORT"
echo "id: $UUID"
