#!/bin/bash

mkdir -p /var/log/v2ray
PORT=$((1000 + RANDOM))
PORT1=$((PORT + 1))
sed -i "s/\"port\":\ 10086/\"port\":\ ${PORT}/g" "/etc/v2ray/server.json"
sed -i "s/\"port\":\ 10087/\"port\":\ ${PORT1}/g" "/etc/v2ray/server.json"
sed -i "s/\"port\":\ 10086/\"port\":\ ${PORT}/g" "/etc/v2ray/client.json"
UUID=$(cat /proc/sys/kernel/random/uuid)
sed -i "s/23ad6b10-8d1a-40f7-8ad0-e3e35cd38297/${UUID}/g" "/etc/v2ray/server.json"
sed -i "s/23ad6b10-8d1a-40f7-8ad0-e3e35cd38297/${UUID}/g" "/etc/v2ray/client.json"
ln -s /etc/v2ray/server.json /etc/v2ray/config.json
systemctl enable v2ray
systemctl start v2ray
echo "port: $PORT"
echo "id: $UUID"
